// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: archived_interfaces.sql

package godevmandb

import (
	"context"
	"time"

	"github.com/jackc/pgtype"
)

const CountArchivedInterfaces = `-- name: CountArchivedInterfaces :one
SELECT COUNT(*)
FROM archived_interfaces
`

func (q *Queries) CountArchivedInterfaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountArchivedInterfaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateArchivedInterface = `-- name: CreateArchivedInterface :one
INSERT INTO archived_interfaces (
    ifindex,
    otn_if_id,
    cisco_opt_power_index,
    hostname,
    host_ip4,
    host_ip6,
    manufacturer,
    model,
    descr,
    alias,
    type_enum,
    mac
  )
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
  )
RETURNING ifa_id, ifindex, otn_if_id, cisco_opt_power_index, hostname, host_ip4, host_ip6, manufacturer, model, descr, alias, type_enum, mac, updated_on, created_on
`

type CreateArchivedInterfaceParams struct {
	Ifindex            *int64         `json:"ifindex"`
	OtnIfID            *int64         `json:"otn_if_id"`
	CiscoOptPowerIndex *string        `json:"cisco_opt_power_index"`
	Hostname           string         `json:"hostname"`
	HostIp4            pgtype.Inet    `json:"host_ip4"`
	HostIp6            pgtype.Inet    `json:"host_ip6"`
	Manufacturer       string         `json:"manufacturer"`
	Model              string         `json:"model"`
	Descr              string         `json:"descr"`
	Alias              *string        `json:"alias"`
	TypeEnum           *int16         `json:"type_enum"`
	Mac                pgtype.Macaddr `json:"mac"`
}

func (q *Queries) CreateArchivedInterface(ctx context.Context, arg CreateArchivedInterfaceParams) (ArchivedInterface, error) {
	row := q.db.QueryRow(ctx, CreateArchivedInterface,
		arg.Ifindex,
		arg.OtnIfID,
		arg.CiscoOptPowerIndex,
		arg.Hostname,
		arg.HostIp4,
		arg.HostIp6,
		arg.Manufacturer,
		arg.Model,
		arg.Descr,
		arg.Alias,
		arg.TypeEnum,
		arg.Mac,
	)
	var i ArchivedInterface
	err := row.Scan(
		&i.IfaID,
		&i.Ifindex,
		&i.OtnIfID,
		&i.CiscoOptPowerIndex,
		&i.Hostname,
		&i.HostIp4,
		&i.HostIp6,
		&i.Manufacturer,
		&i.Model,
		&i.Descr,
		&i.Alias,
		&i.TypeEnum,
		&i.Mac,
		&i.UpdatedOn,
		&i.CreatedOn,
	)
	return i, err
}

const DeleteArchivedInterface = `-- name: DeleteArchivedInterface :exec
DELETE FROM archived_interfaces
WHERE ifa_id = $1
`

func (q *Queries) DeleteArchivedInterface(ctx context.Context, ifaID int64) error {
	_, err := q.db.Exec(ctx, DeleteArchivedInterface, ifaID)
	return err
}

const GetArchivedInterface = `-- name: GetArchivedInterface :one
SELECT ifa_id, ifindex, otn_if_id, cisco_opt_power_index, hostname, host_ip4, host_ip6, manufacturer, model, descr, alias, type_enum, mac, updated_on, created_on
FROM archived_interfaces
WHERE ifa_id = $1
`

func (q *Queries) GetArchivedInterface(ctx context.Context, ifaID int64) (ArchivedInterface, error) {
	row := q.db.QueryRow(ctx, GetArchivedInterface, ifaID)
	var i ArchivedInterface
	err := row.Scan(
		&i.IfaID,
		&i.Ifindex,
		&i.OtnIfID,
		&i.CiscoOptPowerIndex,
		&i.Hostname,
		&i.HostIp4,
		&i.HostIp6,
		&i.Manufacturer,
		&i.Model,
		&i.Descr,
		&i.Alias,
		&i.TypeEnum,
		&i.Mac,
		&i.UpdatedOn,
		&i.CreatedOn,
	)
	return i, err
}

const GetArchivedInterfaces = `-- name: GetArchivedInterfaces :many
SELECT ifa_id, ifindex, otn_if_id, cisco_opt_power_index, hostname, host_ip4, host_ip6, manufacturer, model, descr, alias, type_enum, mac, updated_on, created_on
FROM archived_interfaces
WHERE (
    $1::TIMESTAMPTZ = '0001-01-01 00:00:00+00'
    OR updated_on >= $1
  )
  AND (
    $2::TIMESTAMPTZ = '0001-01-01 00:00:00+00'
    OR updated_on <= $2
  )
  AND (
    $3::TIMESTAMPTZ = '0001-01-01 00:00:00+00'
    OR created_on >= $3
  )
  AND (
    $4::TIMESTAMPTZ = '0001-01-01 00:00:00+00'
    OR created_on <= $4
  )
  AND (
    $5::text IS NULL
    OR ($5::text = 'isnull' AND ifindex IS NULL)
    OR ($5::text = 'isempty' AND CAST(ifindex AS text) = '')
    OR CAST(ifindex AS text) LIKE $5
  )
  AND (
    $6::text IS NULL
    OR ($6::text = 'isnull' AND otn_if_id IS NULL)
    OR ($6::text = 'isempty' AND CAST(otn_if_id AS text) = '')
    OR CAST(otn_if_id AS text) LIKE $6
  )
  AND (
    $7::text IS NULL
    OR ($7::text = 'isnull' AND cisco_opt_power_index IS NULL)
    OR ($7::text = 'isempty' AND cisco_opt_power_index = '')
    OR cisco_opt_power_index ILIKE $7
  )
  AND (
    $8::text = ''
    OR ($8  = 'isempty' AND hostname = '')
    OR hostname ILIKE $8
  )
  AND (
    $9::inet IS NULL
    OR host_ip4 <<= $9
  )
  AND (
    $10::inet IS NULL
    OR host_ip6 <<= $10
  )
  AND (
    $11::text = ''
    OR ($11 = 'isempty' AND manufacturer = '')
    OR manufacturer ILIKE $11
  )
  AND (
    $12::text = ''
    OR ($12  = 'isempty' AND model = '')
    OR model ILIKE $12
  )
  AND (
    $13::text = ''
    OR ($13  = 'isempty' AND descr = '')
    OR descr ILIKE $13
  )
  AND (
    $14::text IS NULL
    OR ($14::text = 'isnull' AND alias IS NULL)
    OR ($14::text = 'isempty' AND alias = '')
    OR alias ILIKE $14
  )
  AND (
    $15::text IS NULL
    OR ($15::text = 'isnull' AND type_enum IS NULL)
    OR ($15::text = 'isempty' AND CAST(type_enum AS text) = '')
    OR CAST(type_enum AS text) LIKE $15
  )
  AND (
    $16::macaddr IS NULL
    OR mac = $16
  )
ORDER BY created_on
LIMIT NULLIF($18::int, 0) OFFSET NULLIF($17::int, 0)
`

type GetArchivedInterfacesParams struct {
	UpdatedGe           time.Time      `json:"updated_ge"`
	UpdatedLe           time.Time      `json:"updated_le"`
	CreatedGe           time.Time      `json:"created_ge"`
	CreatedLe           time.Time      `json:"created_le"`
	IfindexF            *string        `json:"ifindex_f"`
	OtnIfIDF            *string        `json:"otn_if_id_f"`
	CiscoOptPowerIndexF *string        `json:"cisco_opt_power_index_f"`
	HostnameF           string         `json:"hostname_f"`
	HostIp4F            pgtype.Inet    `json:"host_ip4_f"`
	HostIp6F            pgtype.Inet    `json:"host_ip6_f"`
	ManufacturerF       string         `json:"manufacturer_f"`
	ModelF              string         `json:"model_f"`
	DescrF              string         `json:"descr_f"`
	AliasF              *string        `json:"alias_f"`
	TypeEnumF           *string        `json:"type_enum_f"`
	MacF                pgtype.Macaddr `json:"mac_f"`
	OffsetQ             int32          `json:"offset_q"`
	LimitQ              int32          `json:"limit_q"`
}

func (q *Queries) GetArchivedInterfaces(ctx context.Context, arg GetArchivedInterfacesParams) ([]ArchivedInterface, error) {
	rows, err := q.db.Query(ctx, GetArchivedInterfaces,
		arg.UpdatedGe,
		arg.UpdatedLe,
		arg.CreatedGe,
		arg.CreatedLe,
		arg.IfindexF,
		arg.OtnIfIDF,
		arg.CiscoOptPowerIndexF,
		arg.HostnameF,
		arg.HostIp4F,
		arg.HostIp6F,
		arg.ManufacturerF,
		arg.ModelF,
		arg.DescrF,
		arg.AliasF,
		arg.TypeEnumF,
		arg.MacF,
		arg.OffsetQ,
		arg.LimitQ,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArchivedInterface
	for rows.Next() {
		var i ArchivedInterface
		if err := rows.Scan(
			&i.IfaID,
			&i.Ifindex,
			&i.OtnIfID,
			&i.CiscoOptPowerIndex,
			&i.Hostname,
			&i.HostIp4,
			&i.HostIp6,
			&i.Manufacturer,
			&i.Model,
			&i.Descr,
			&i.Alias,
			&i.TypeEnum,
			&i.Mac,
			&i.UpdatedOn,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateArchivedInterface = `-- name: UpdateArchivedInterface :one
UPDATE archived_interfaces
SET ifindex = $2,
  otn_if_id = $3,
  cisco_opt_power_index = $4,
  hostname = $5,
  host_ip4 = $6,
  host_ip6 = $7,
  manufacturer = $8,
  model = $9,
  descr = $10,
  alias = $11,
  type_enum = $12,
  mac = $13
WHERE ifa_id = $1
RETURNING ifa_id, ifindex, otn_if_id, cisco_opt_power_index, hostname, host_ip4, host_ip6, manufacturer, model, descr, alias, type_enum, mac, updated_on, created_on
`

type UpdateArchivedInterfaceParams struct {
	IfaID              int64          `json:"ifa_id"`
	Ifindex            *int64         `json:"ifindex"`
	OtnIfID            *int64         `json:"otn_if_id"`
	CiscoOptPowerIndex *string        `json:"cisco_opt_power_index"`
	Hostname           string         `json:"hostname"`
	HostIp4            pgtype.Inet    `json:"host_ip4"`
	HostIp6            pgtype.Inet    `json:"host_ip6"`
	Manufacturer       string         `json:"manufacturer"`
	Model              string         `json:"model"`
	Descr              string         `json:"descr"`
	Alias              *string        `json:"alias"`
	TypeEnum           *int16         `json:"type_enum"`
	Mac                pgtype.Macaddr `json:"mac"`
}

func (q *Queries) UpdateArchivedInterface(ctx context.Context, arg UpdateArchivedInterfaceParams) (ArchivedInterface, error) {
	row := q.db.QueryRow(ctx, UpdateArchivedInterface,
		arg.IfaID,
		arg.Ifindex,
		arg.OtnIfID,
		arg.CiscoOptPowerIndex,
		arg.Hostname,
		arg.HostIp4,
		arg.HostIp6,
		arg.Manufacturer,
		arg.Model,
		arg.Descr,
		arg.Alias,
		arg.TypeEnum,
		arg.Mac,
	)
	var i ArchivedInterface
	err := row.Scan(
		&i.IfaID,
		&i.Ifindex,
		&i.OtnIfID,
		&i.CiscoOptPowerIndex,
		&i.Hostname,
		&i.HostIp4,
		&i.HostIp6,
		&i.Manufacturer,
		&i.Model,
		&i.Descr,
		&i.Alias,
		&i.TypeEnum,
		&i.Mac,
		&i.UpdatedOn,
		&i.CreatedOn,
	)
	return i, err
}
