// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: archived_interfaces.sql

package godevmandb

import (
	"context"
	"database/sql"

	"github.com/jackc/pgtype"
)

const CountArchivedInterfaces = `-- name: CountArchivedInterfaces :one
SELECT COUNT(*)
FROM archived_interfaces
`

func (q *Queries) CountArchivedInterfaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountArchivedInterfaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateArchivedInterface = `-- name: CreateArchivedInterface :one
INSERT INTO archived_interfaces (
    ifindex,
    otn_if_id,
    cisco_opt_power_index,
    hostname,
    host_ip4,
    host_ip6,
    manufacturer,
    model,
    descr,
    alias,
    type_enum,
    mac
  )
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
  )
RETURNING ifa_id, ifindex, otn_if_id, cisco_opt_power_index, hostname, host_ip4, host_ip6, manufacturer, model, descr, alias, type_enum, mac, updated_on, created_on
`

type CreateArchivedInterfaceParams struct {
	Ifindex            sql.NullInt64  `json:"ifindex"`
	OtnIfID            sql.NullInt64  `json:"otn_if_id"`
	CiscoOptPowerIndex sql.NullString `json:"cisco_opt_power_index"`
	Hostname           string         `json:"hostname"`
	HostIp4            pgtype.Inet    `json:"host_ip4"`
	HostIp6            pgtype.Inet    `json:"host_ip6"`
	Manufacturer       string         `json:"manufacturer"`
	Model              string         `json:"model"`
	Descr              string         `json:"descr"`
	Alias              sql.NullString `json:"alias"`
	TypeEnum           sql.NullInt16  `json:"type_enum"`
	Mac                pgtype.Macaddr `json:"mac"`
}

func (q *Queries) CreateArchivedInterface(ctx context.Context, arg CreateArchivedInterfaceParams) (ArchivedInterface, error) {
	row := q.db.QueryRow(ctx, CreateArchivedInterface,
		arg.Ifindex,
		arg.OtnIfID,
		arg.CiscoOptPowerIndex,
		arg.Hostname,
		arg.HostIp4,
		arg.HostIp6,
		arg.Manufacturer,
		arg.Model,
		arg.Descr,
		arg.Alias,
		arg.TypeEnum,
		arg.Mac,
	)
	var i ArchivedInterface
	err := row.Scan(
		&i.IfaID,
		&i.Ifindex,
		&i.OtnIfID,
		&i.CiscoOptPowerIndex,
		&i.Hostname,
		&i.HostIp4,
		&i.HostIp6,
		&i.Manufacturer,
		&i.Model,
		&i.Descr,
		&i.Alias,
		&i.TypeEnum,
		&i.Mac,
		&i.UpdatedOn,
		&i.CreatedOn,
	)
	return i, err
}

const DeleteArchivedInterface = `-- name: DeleteArchivedInterface :exec
DELETE FROM archived_interfaces
WHERE ifa_id = $1
`

func (q *Queries) DeleteArchivedInterface(ctx context.Context, ifaID int64) error {
	_, err := q.db.Exec(ctx, DeleteArchivedInterface, ifaID)
	return err
}

const GetArchivedInterface = `-- name: GetArchivedInterface :one
SELECT ifa_id, ifindex, otn_if_id, cisco_opt_power_index, hostname, host_ip4, host_ip6, manufacturer, model, descr, alias, type_enum, mac, updated_on, created_on
FROM archived_interfaces
WHERE ifa_id = $1
`

func (q *Queries) GetArchivedInterface(ctx context.Context, ifaID int64) (ArchivedInterface, error) {
	row := q.db.QueryRow(ctx, GetArchivedInterface, ifaID)
	var i ArchivedInterface
	err := row.Scan(
		&i.IfaID,
		&i.Ifindex,
		&i.OtnIfID,
		&i.CiscoOptPowerIndex,
		&i.Hostname,
		&i.HostIp4,
		&i.HostIp6,
		&i.Manufacturer,
		&i.Model,
		&i.Descr,
		&i.Alias,
		&i.TypeEnum,
		&i.Mac,
		&i.UpdatedOn,
		&i.CreatedOn,
	)
	return i, err
}

const GetArchivedInterfaces = `-- name: GetArchivedInterfaces :many
SELECT ifa_id, ifindex, otn_if_id, cisco_opt_power_index, hostname, host_ip4, host_ip6, manufacturer, model, descr, alias, type_enum, mac, updated_on, created_on
FROM archived_interfaces
ORDER BY descr
LIMIT $1
OFFSET $2
`

type GetArchivedInterfacesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetArchivedInterfaces(ctx context.Context, arg GetArchivedInterfacesParams) ([]ArchivedInterface, error) {
	rows, err := q.db.Query(ctx, GetArchivedInterfaces, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArchivedInterface
	for rows.Next() {
		var i ArchivedInterface
		if err := rows.Scan(
			&i.IfaID,
			&i.Ifindex,
			&i.OtnIfID,
			&i.CiscoOptPowerIndex,
			&i.Hostname,
			&i.HostIp4,
			&i.HostIp6,
			&i.Manufacturer,
			&i.Model,
			&i.Descr,
			&i.Alias,
			&i.TypeEnum,
			&i.Mac,
			&i.UpdatedOn,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateArchivedInterface = `-- name: UpdateArchivedInterface :one
UPDATE archived_interfaces
SET ifindex = $2,
  otn_if_id = $3,
  cisco_opt_power_index = $4,
  hostname = $5,
  host_ip4 = $6,
  host_ip6 = $7,
  manufacturer = $8,
  model = $9,
  descr = $10,
  alias = $11,
  type_enum = $12,
  mac = $13
WHERE ifa_id = $1
RETURNING ifa_id, ifindex, otn_if_id, cisco_opt_power_index, hostname, host_ip4, host_ip6, manufacturer, model, descr, alias, type_enum, mac, updated_on, created_on
`

type UpdateArchivedInterfaceParams struct {
	IfaID              int64          `json:"ifa_id"`
	Ifindex            sql.NullInt64  `json:"ifindex"`
	OtnIfID            sql.NullInt64  `json:"otn_if_id"`
	CiscoOptPowerIndex sql.NullString `json:"cisco_opt_power_index"`
	Hostname           string         `json:"hostname"`
	HostIp4            pgtype.Inet    `json:"host_ip4"`
	HostIp6            pgtype.Inet    `json:"host_ip6"`
	Manufacturer       string         `json:"manufacturer"`
	Model              string         `json:"model"`
	Descr              string         `json:"descr"`
	Alias              sql.NullString `json:"alias"`
	TypeEnum           sql.NullInt16  `json:"type_enum"`
	Mac                pgtype.Macaddr `json:"mac"`
}

func (q *Queries) UpdateArchivedInterface(ctx context.Context, arg UpdateArchivedInterfaceParams) (ArchivedInterface, error) {
	row := q.db.QueryRow(ctx, UpdateArchivedInterface,
		arg.IfaID,
		arg.Ifindex,
		arg.OtnIfID,
		arg.CiscoOptPowerIndex,
		arg.Hostname,
		arg.HostIp4,
		arg.HostIp6,
		arg.Manufacturer,
		arg.Model,
		arg.Descr,
		arg.Alias,
		arg.TypeEnum,
		arg.Mac,
	)
	var i ArchivedInterface
	err := row.Scan(
		&i.IfaID,
		&i.Ifindex,
		&i.OtnIfID,
		&i.CiscoOptPowerIndex,
		&i.Hostname,
		&i.HostIp4,
		&i.HostIp6,
		&i.Manufacturer,
		&i.Model,
		&i.Descr,
		&i.Alias,
		&i.TypeEnum,
		&i.Mac,
		&i.UpdatedOn,
		&i.CreatedOn,
	)
	return i, err
}
