// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: con_providers.sql

package godevmandb

import (
	"context"
	"database/sql"
)

const CountConProviders = `-- name: CountConProviders :one
SELECT COUNT(*)
FROM con_providers
`

func (q *Queries) CountConProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountConProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateConProvider = `-- name: CreateConProvider :one
INSERT INTO con_providers (descr, notes)
VALUES ($1, $2)
RETURNING con_prov_id, descr, notes, updated_on, created_on
`

type CreateConProviderParams struct {
	Descr string         `json:"descr"`
	Notes sql.NullString `json:"notes"`
}

func (q *Queries) CreateConProvider(ctx context.Context, arg CreateConProviderParams) (ConProvider, error) {
	row := q.db.QueryRow(ctx, CreateConProvider, arg.Descr, arg.Notes)
	var i ConProvider
	err := row.Scan(
		&i.ConProvID,
		&i.Descr,
		&i.Notes,
		&i.UpdatedOn,
		&i.CreatedOn,
	)
	return i, err
}

const DeleteConProvider = `-- name: DeleteConProvider :exec
DELETE FROM con_providers
WHERE con_prov_id = $1
`

func (q *Queries) DeleteConProvider(ctx context.Context, conProvID int64) error {
	_, err := q.db.Exec(ctx, DeleteConProvider, conProvID)
	return err
}

const GetConProvider = `-- name: GetConProvider :one
SELECT con_prov_id, descr, notes, updated_on, created_on
FROM con_providers
WHERE con_prov_id = $1
`

func (q *Queries) GetConProvider(ctx context.Context, conProvID int64) (ConProvider, error) {
	row := q.db.QueryRow(ctx, GetConProvider, conProvID)
	var i ConProvider
	err := row.Scan(
		&i.ConProvID,
		&i.Descr,
		&i.Notes,
		&i.UpdatedOn,
		&i.CreatedOn,
	)
	return i, err
}

const GetConProviderConnections = `-- name: GetConProviderConnections :many
SELECT con_id, site_id, con_prov_id, con_type_id, con_cap_id, con_class_id, hint, notes, in_use, updated_on, created_on
FROM connections
WHERE con_prov_id = $1
`

// Relations
func (q *Queries) GetConProviderConnections(ctx context.Context, conProvID int64) ([]Connection, error) {
	rows, err := q.db.Query(ctx, GetConProviderConnections, conProvID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ConID,
			&i.SiteID,
			&i.ConProvID,
			&i.ConTypeID,
			&i.ConCapID,
			&i.ConClassID,
			&i.Hint,
			&i.Notes,
			&i.InUse,
			&i.UpdatedOn,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetConProviders = `-- name: GetConProviders :many
SELECT con_prov_id, descr, notes, updated_on, created_on
FROM con_providers
ORDER BY descr
LIMIT $1
OFFSET $2
`

type GetConProvidersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetConProviders(ctx context.Context, arg GetConProvidersParams) ([]ConProvider, error) {
	rows, err := q.db.Query(ctx, GetConProviders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConProvider
	for rows.Next() {
		var i ConProvider
		if err := rows.Scan(
			&i.ConProvID,
			&i.Descr,
			&i.Notes,
			&i.UpdatedOn,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateConProvider = `-- name: UpdateConProvider :one
UPDATE con_providers
SET descr = $2,
  notes = $3
WHERE con_prov_id = $1
RETURNING con_prov_id, descr, notes, updated_on, created_on
`

type UpdateConProviderParams struct {
	ConProvID int64          `json:"con_prov_id"`
	Descr     string         `json:"descr"`
	Notes     sql.NullString `json:"notes"`
}

func (q *Queries) UpdateConProvider(ctx context.Context, arg UpdateConProviderParams) (ConProvider, error) {
	row := q.db.QueryRow(ctx, UpdateConProvider, arg.ConProvID, arg.Descr, arg.Notes)
	var i ConProvider
	err := row.Scan(
		&i.ConProvID,
		&i.Descr,
		&i.Notes,
		&i.UpdatedOn,
		&i.CreatedOn,
	)
	return i, err
}
